Repository chrisleekr/binance-trading-bot, pull requests merged in 2022-08, with the labels that each got.

#452 fix: ui improvements
  public/css/App.css
  public/js/App.js
  public/js/CoinWrapperAction.js
  public/js/CoinWrapperBuySignal.js
  public/js/CoinWrapperSellSignal.js
  public/js/QuoteAssetGridTradeArchiveIcon.js
  public/js/SymbolGridTradeArchiveIcon.js
  public/js/SymbolLogsIcon.js
Labels: enhancement

#454 fix: closed trades timezone consistency
  CHANGELOG.md
  app/cronjob/trailingTrade/step/__tests__/determine-action.test.js
  app/cronjob/trailingTrade/step/determine-action.js
  app/cronjob/trailingTrade/step/ensure-grid-trade-order-executed.js
  app/cronjob/trailingTrade/step/ensure-manual-order.js
  app/cronjob/trailingTrade/step/get-balances.js
  app/cronjob/trailingTrade/step/get-override-action.js
  app/cronjob/trailingTrade/step/handle-open-orders.js
  app/cronjob/trailingTrade/step/place-buy-order.js
  app/cronjob/trailingTrade/step/remove-last-buy-price.js
  app/cronjob/trailingTradeHelper/configuration.js
  app/cronjob/trailingTradeIndicator/step/__tests__/get-closed-trades.test.js
  app/cronjob/trailingTradeIndicator/step/get-closed-trades.js
  app/frontend/webserver/handlers/closed-trades-set-period.js
  app/frontend/websocket/handlers/cancel-order.js
  app/frontend/websocket/handlers/dust-transfer-execute.js
  app/frontend/websocket/handlers/manual-trade-all-symbols.js
  app/frontend/websocket/handlers/manual-trade.js
  app/frontend/websocket/handlers/symbol-trigger-buy.js
  app/frontend/websocket/handlers/symbol-trigger-sell.js
  app/helpers/logger.js
  app/server-binance.js
  public/index.html
  public/index.prod.html
  public/js/CoinWrapperAction.js
  public/js/ProfitLossWrapper.js
  public/js/QuoteAssetGridTradeArchiveIcon.js
  public/js/SymbolGridTradeArchiveIcon.js
Labels: bug

#464 feat: introduce queue ✨
  app/__tests__/server-binance.test.js
  app/__tests__/server-frontend.test.js
  app/binance/__tests__/tickers.test.js
  app/binance/__tests__/user.test.js
  app/binance/tickers.js
  app/binance/user.js
  app/cronjob/__tests__/trailingTrade.test.js
  app/cronjob/trailingTrade.js
  app/cronjob/trailingTradeHelper/__tests__/queue.test.js
  app/cronjob/trailingTradeHelper/queue.js
  app/error-handler.js
  app/frontend/bull-board/__tests__/configure.test.js
  app/frontend/bull-board/configure.js
  app/frontend/webserver/handlers/404.js
  app/frontend/webserver/handlers/__tests__/404.test.js
  app/frontend/websocket/handlers/__tests__/cancel-order.test.js
  app/frontend/websocket/handlers/__tests__/manual-trade-all-symbols.test.js
  app/frontend/websocket/handlers/__tests__/manual-trade.test.js
  app/frontend/websocket/handlers/__tests__/symbol-enable-action.test.js
  app/frontend/websocket/handlers/__tests__/symbol-grid-trade-delete.test.js
  app/frontend/websocket/handlers/__tests__/symbol-setting-delete.test.js
  app/frontend/websocket/handlers/__tests__/symbol-setting-update.test.js
  app/frontend/websocket/handlers/__tests__/symbol-trigger-buy.test.js
  app/frontend/websocket/handlers/__tests__/symbol-trigger-sell.test.js
  app/frontend/websocket/handlers/__tests__/symbol-update-last-buy-price.test.js
  app/frontend/websocket/handlers/cancel-order.js
  app/frontend/websocket/handlers/manual-trade-all-symbols.js
  app/frontend/websocket/handlers/manual-trade.js
  app/frontend/websocket/handlers/symbol-enable-action.js
  app/frontend/websocket/handlers/symbol-grid-trade-delete.js
  app/frontend/websocket/handlers/symbol-setting-delete.js
  app/frontend/websocket/handlers/symbol-setting-update.js
  app/frontend/websocket/handlers/symbol-trigger-buy.js
  app/frontend/websocket/handlers/symbol-trigger-sell.js
  app/frontend/websocket/handlers/symbol-update-last-buy-price.js
  app/server-binance.js
  app/server-frontend.js
  package-lock.json
  package.json
  public/js/CoinWrapperAction.js
Labels: enhancement

#462 fix: exceeding max open trades
  CHANGELOG.md
  app/__tests__/server-binance.test.js
  app/cronjob/trailingTrade/step/__tests__/determine-action.test.js
  app/cronjob/trailingTrade/step/__tests__/ensure-grid-trade-order-executed.test.js
  app/cronjob/trailingTrade/step/__tests__/handle-open-orders.test.js
  app/cronjob/trailingTrade/step/cancel-order.js
  app/cronjob/trailingTrade/step/determine-action.js
  app/cronjob/trailingTrade/step/ensure-grid-trade-order-executed.js
  app/cronjob/trailingTrade/step/handle-open-orders.js
  app/cronjob/trailingTrade/step/place-buy-order.js
  app/cronjob/trailingTrade/step/place-manual-trade.js
  app/cronjob/trailingTrade/step/place-sell-order.js
  app/cronjob/trailingTrade/step/place-sell-stop-loss-order.js
  app/cronjob/trailingTradeHelper/__tests__/common.test.js
  app/cronjob/trailingTradeHelper/common.js
  app/server-binance.js
Labels: bug

#479 feat: improve UI
  app/cronjob/trailingTrade/step/__tests__/cancel-order.test.js
  app/cronjob/trailingTrade/step/cancel-order.js
  app/cronjob/trailingTradeHelper/__tests__/common.test.js
  app/cronjob/trailingTradeHelper/common.js
  app/cronjob/trailingTradeIndicator/step/__tests__/get-closed-trades.test.js
  app/cronjob/trailingTradeIndicator/step/get-closed-trades.js
  app/frontend/websocket/handlers/__tests__/cancel-order.test.js
  app/frontend/websocket/handlers/cancel-order.js
  public/css/App.css
  public/js/AccountWrapper.js
  public/js/AccountWrapperAsset.js
  public/js/App.js
  public/js/CoinWrapperAction.js
  public/js/CoinWrapperBuySignal.js
  public/js/CoinWrapperSellSignal.js
  public/js/CoinWrapperTradingView.js
  public/js/ProfitLossWrapper.js
  public/js/QuoteAssetGridTradeArchiveIcon.js
  public/js/SymbolGridTradeArchiveIcon.js
Labels: enhancement

#478 fix: non-active exchange symbols
  app/binance/__tests__/candles.test.js
  app/binance/candles.js
  app/cronjob/trailingTrade/step/__tests__/get-indicators.test.js
  app/cronjob/trailingTrade/step/get-indicators.js
  app/cronjob/trailingTradeHelper/__tests__/common.test.js
  app/cronjob/trailingTradeHelper/__tests__/fixtures/binance-cached-exchange-symbols.json
  app/cronjob/trailingTradeHelper/common.js
  public/css/App.css
  public/index.html
  public/index.prod.html
  public/js/CoinWrapperSymbol.js
  public/js/SettingIcon.js
Labels: bug, enhancement

#481 perf: bulk write candles to db
  app/binance/__tests__/ath-candles.test.js
  app/binance/__tests__/candles.test.js
  app/binance/ath-candles.js
  app/binance/candles.js
  app/helpers/__tests__/mongo.test.js
  app/helpers/mongo.js
Labels: enhancement

#489 chore: remove override data when remove symbol from the list
  app/frontend/webserver/handlers/__tests__/index.test.js
  app/frontend/webserver/handlers/__tests__/symbol-delete.test.js
  app/frontend/webserver/handlers/index.js
  app/frontend/webserver/handlers/symbol-delete.js
  app/frontend/websocket/__tests__/configure.test.js
  app/frontend/websocket/configure.js
  app/frontend/websocket/handlers/__tests__/index.test.js
  app/frontend/websocket/handlers/index.js
  package-lock.json
  public/js/ProfitLossWrapper.js
  public/js/QuoteAssetGridTradeArchiveIcon.js
  public/js/SymbolDeleteIcon.js
Labels: enhancement

#490 fix: archive grid order if all sell orders are executed
  app/cronjob/trailingTrade/step/__tests__/remove-last-buy-price.test.js
  app/cronjob/trailingTrade/step/remove-last-buy-price.js
Labels: bug

#495 fix: handle execution report
  app/binance/user.js
  app/cronjob/trailingTrade/step/__tests__/ensure-grid-trade-order-executed.test.js
  app/cronjob/trailingTrade/step/ensure-grid-trade-order-executed.js
Labels: bug
